version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - bookstack_net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=your@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - bookstack_net

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:e+a+iNSPR1dPRb1z0ujLve2XTyqmrifWza/0ssF1rp4=
      - APP_LANG=kr
      - TZ=Asia/Seoul
      - APP_URL=https://dainwiki.com
      - DB_HOST=bookstack_db
      - DB_DATABASE=bookstack
      - DB_USER=bookstack
      - DB_PASS=MySecret123!
      - VIRTUAL_HOST=dainwiki.com
      - LETSENCRYPT_HOST=dainwiki.com
      - LETSENCRYPT_EMAIL=your@email.com
    volumes:
      - ./bookstack_data:/config
    depends_on:
      - bookstack_db
    networks:
      - bookstack_net

  bookstack_db:
    image: mariadb:10.4
    container_name: bookstack_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=MySecret123!
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - bookstack_net

networks:
  bookstack_net:
    driver: bridge

